#!/usr/bin/python3

import argparse
from xmlrpc.client import ServerProxy
from sys import exit, stderr

parser = argparse.ArgumentParser(
    description="Configures the video input to display on the Chamelium's VGA output"
)
parser.add_argument("chamelium_host", help="The Chamelium to configure",
                    type=lambda host: ServerProxy(host, use_builtin_types=True,
                                                  allow_none=True))
parser.add_argument("port", help="The port to display on the VGA out",
                    type=int)
args = parser.parse_args()

args.chamelium_host.DetectResolution(args.port)

# vim: ft=python :
